# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sureau_ecos_py',
                'doc_host': 'https://ecamo19.github.io',
                'git_url': 'https://github.com/ecamo19/sureau_ecos_py',
                'lib_path': 'sureau_ecos_py'},
  'syms': {'sureau_ecos_py.core': {'sureau_ecos_py.core.foo': ('core.html#foo', 'sureau_ecos_py/core.py')}}}
