# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_calculate_rh_diurnal_pattern.ipynb.

# %% auto 0
__all__ = ['calculate_rh_diurnal_pattern']

# %% ../nbs/05_calculate_rh_diurnal_pattern.ipynb 3
def calculate_rh_diurnal_pattern(
    temperature: float,
    rhmin: float,  # No info in source code
    rhmax: float,  # No info in source code
    tmin: float,  # No info in source code
    tmax: float,  # No info in source code
):
    "Calculate diurnal pattern of relative humidity from temperature"

    # calculate rh diurnal pattern ----------------------------------------
    return rhmax + ((temperature - tmin) / (tmax - tmin)) * (rhmin - rhmax)
