# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_17_calculate_ebound_granier.ipynb.

# %% auto 0
__all__ = ['calculate_ebound_granier']

# %% ../nbs/10_17_calculate_ebound_granier.ipynb 3
import numpy as np
from .calculate_ebound_mm_granier import calculate_ebound_mm_granier
from .convert_flux_from_mm_to_mmolm2s import convert_flux_from_mm_to_mmolm2s

# %% ../nbs/10_17_calculate_ebound_granier.ipynb 4
def calculate_ebound_granier(etp:float, # Unknown parameter definition
                            lai:float, # Leaf area index of the stand (m2leaf.m-2soil)
                            time_step:float, # Time step (in hours)
                            ) -> float:

        "No description found in R source code"

        ebound_mm = calculate_ebound_mm_granier(etp = etp,
                                                lai = lai)

        return convert_flux_from_mm_to_mmolm2s(x = ebound_mm,
                                               time_step = time_step,
                                               lai = lai)

