# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_16_calculate_ebound_mm_granier.ipynb.

# %% auto 0
__all__ = ['calculate_ebound_mm_granier']

# %% ../nbs/10_16_calculate_ebound_mm_granier.ipynb 3
import numpy as np

# %% ../nbs/10_16_calculate_ebound_mm_granier.ipynb 4
def calculate_ebound_mm_granier(etp:float, # Unknown parameter definition
                                lai:float, # Leaf area index of the stand (m2leaf.m-2soil)
                                a:float = -0.006, # Unknown parameter definition
                                b:float = 0.134, # Unknown parameter definition
                                c:float = 0 # Unknown parameter definition
    ) -> float:

        "No description found in R source code"

        # Get the maximum value
        # Example of np.maximum: np.maximum(5, [1,2,6]) == array([5, 5, 6])
        return np.maximum(0, etp * (a * lai**2 + b * lai + c))


