# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_calculate_rh_diurnal_pattern.ipynb.

# %% auto 0
__all__ = ['calculate_rh_diurnal_pattern']

# %% ../nbs/05_calculate_rh_diurnal_pattern.ipynb 3
def calculate_rh_diurnal_pattern(
    temperature: float, # Unknown parameter definition
    rhmin: float,  # Unknown parameter definition
    rhmax: float,  # Unknown parameter definition
    tmin: float,  # Unknown parameter definition
    tmax: float,  # Unknown parameter definition
)->float:
    "Calculate diurnal pattern of relative humidity from temperature"

    # calculate rh diurnal pattern ----------------------------------------------
    return rhmax + ((temperature - tmin) / (tmax - tmin)) * (rhmin - rhmax)
