# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_12_compute_dfmc.ipynb.

# %% auto 0
__all__ = ['compute_dfmc']

# %% ../nbs/10_12_compute_dfmc.ipynb 3
import numpy as np

# %% ../nbs/10_12_compute_dfmc.ipynb 4
def compute_dfmc(vpd:float, # Vapor pressure deficit (kPA)
                 fm0 = 5.43, # Minimum fuel moisture content (% dry weight)
                 fm1 = 52.91, # Maximum fuel moisture content (% dry weight)
                 m = 0.64 # Rate of decay
                 ) -> float: # Fuel moisture content (% dry weight)

        "Compute dead fuel moisture content from VPD following De Dios et al. (2015)"
        return fm0 + fm1 * np.exp(-m * vpd)
