# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_7_compute_theta_at_given_p_soil.ipynb.

# %% auto 0
__all__ = ['compute_theta_at_given_p_soil']

# %% ../nbs/09_7_compute_theta_at_given_p_soil.ipynb 3
def compute_theta_at_given_p_soil(
    psi_target: float, theta_res: float, theta_sat: float, alpha_vg: float, n_vg: float
):
    return theta_res + (theta_sat - theta_res) / (
        1 + (alpha_vg * psi_target * 10000) ** n_vg
    ) ** (1 - 1 / n_vg)
