# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_1_compute_b.ipynb.

# %% auto 0
__all__ = ['compute_b']

# %% ../nbs/09_1_compute_b.ipynb 3
import numpy as np
from math import pi

# %% ../nbs/09_1_compute_b.ipynb 4
def compute_b(lv: float # length of fine root per unit volume
              )->float:

    "Calculate b used to compute the B of the Gardnar-Cowen model"

    return 1 / np.sqrt(pi * lv)
