# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_14_compute_g_crown.ipynb.

# %% auto 0
__all__ = ['compute_g_crown']

# %% ../nbs/10_14_compute_g_crown.ipynb 3
def compute_g_crown(g_crown0:float, # Unknown parameter definition
                    wind_speed:float # Unknown parameter definition
                    ) -> float:

        "Calcultate g_crown"

        # to avoid very high conductance values
        wind_speed=  max(0.1, wind_speed)

        return g_crown0*wind_speed**0.6
