# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_compute_etp_pm.ipynb.

# %% auto 0
__all__ = ['compute_etp_pm']

# %% ../nbs/02_compute_etp_pm.ipynb 3
import numpy as np

# %% ../nbs/02_compute_etp_pm.ipynb 4
def compute_etp_pm(
    tmoy: float,  # Mean temperature over the considered time step (degrees Celsius)
    net_radiation: float,  # Cumulative Net radiation over the considered  time sep  (MJ.m2)
    u: float,  #  wind speed (m.s-1)
    vpd: float,  # Vapor pressure deficit (kpa)
    g: float = 0,
):
    "Compute reference ETP from Penmman formulation"

    # Constants ---------------------------------------------------------------

    # Stefan-Boltzman constant [MJ.K^-4.m^-2.day^-1]
    sb_constant = 4.903 * 10**9

    # Psychometer constant
    gamma = 0.0666

    # Latent heat of vaporisation
    lamb = 2.45

    # Compute ETP -------------------------------------------------------------

    #  s: slope of the saturation vapour pressure function (AO 1998)
    # delta = 4098 * 0.6108 * exp((17.27 * Tmoy) / (Tmoy + 237.3)) / ((Tmoy + 237.3)^2)
    delta = (
        4098 * 0.6108 * np.exp((17.27 * tmoy) / (tmoy + 237.3)) / ((tmoy + 237.3) ** 2)
    )

    ga = 0.34 * max(u, 0.001)

    u2 = u * (4.87 / np.log(67.8 * 10 - 5.42))

    n1 = 0.408 * delta * net_radiation
    n2 = gamma * (37 / (tmoy + 273)) * u2 * vpd
    d = delta + gamma * (1 + 0.34 * u2)

    # Return E
    return (n1 + n2) / (d)
