# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_11_compute_emin.ipynb.

# %% auto 0
__all__ = ['compute_emin']

# %% ../nbs/10_11_compute_emin.ipynb 3
import numpy as np

# %% ../nbs/10_11_compute_emin.ipynb 4
# Osmotic potential
def compute_emin(gmin:float, # minimum conductance
                 vpd:float,  # Vapor Pressure Deficit  (kPa)
                 g_bl:float, # Unknown parameter definition
                 g_crown:float, # Unknown parameter definition
                 air_pressure:float = 101.3, # Surface air pressure (kPa)
                 ) -> float:

        "Calculate minimum transpiration (emin)"

        gmin_tot = 1/(1/gmin+ 1/g_bl + 1/g_crown)
        return gmin_tot * (vpd /air_pressure)
