# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_2_compute_b_gc.ipynb.

# %% auto 0
__all__ = ['compute_b_gc']

# %% ../nbs/09_2_compute_b_gc.ipynb 3
import numpy as np
from math import pi

# %% ../nbs/09_2_compute_b_gc.ipynb 4
def compute_b_gc(
    la: float, b: float, root_radius: float  # Calculated using the `compute_b` function
):
    "Calculate B Gardner cowen thhe scaling factor for soil conductance"

    return la * 2 * pi / np.log(b / root_radius)
