# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_15_convert_flux_from_mm_to_mmolm2s.ipynb.

# %% auto 0
__all__ = ['convert_flux_from_mm_to_mmolm2s']

# %% ../nbs/10_15_convert_flux_from_mm_to_mmolm2s.ipynb 3
def convert_flux_from_mm_to_mmolm2s(x:float, # The amount of water in mm (L.m-2soil)
                                    time_step:float, # Time step (in hours)
                                    lai:float # Leaf area index of the stand (m2leaf.m-2soil)
                                    ) -> float:

        "Convert flux in L.m-2soil to an instantaneous flux in mmol/m-2leaf.s-1 over a defined time period"
        if lai > 0:
            return (10**6 * x)/(lai * time_step * 3600 * 18)

        else:
            return 0

