# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_18_convert_f_cm3_to_v_mm.ipynb.

# %% auto 0
__all__ = ['convert_f_cm3_to_v_mm']

# %% ../nbs/10_18_convert_f_cm3_to_v_mm.ipynb 3
def convert_f_cm3_to_v_mm(x:float, # Soil value to be converted (in m3.m-3)
                          rock_fragment_content:float, # Rock fragment content of the soil layer (%)
                          layer_thickness:float  # Thickness of the soil layer (in m)
                        ) -> float: # y soil parameter in mm

        "Convert soil parameter from from cm3.cm-3 to mm according to thickness and rock fragment content"
        return x * (1 - (rock_fragment_content / 100)) * layer_thickness * 1000
