# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_15_1_convert_flux_from_mm_to_mmolm2s.ipynb.

# %% auto 0
__all__ = ['convert_flux_from_mmolm2s_to_mm']

# %% ../nbs/10_15_1_convert_flux_from_mm_to_mmolm2s.ipynb 3
def convert_flux_from_mmolm2s_to_mm(x:float, # The amount of water in mm (L.m-2soil)
                                    time_step:float, # Time step (in hours)
                                    lai:float # Leaf area index of the stand (m2leaf.m-2soil)
                                    ) -> float:

        "Convert an instantaneous flux in mmol.m-2Leaf.s-1 to a amount in mm (L.m2soil) over a defined time period"
        return  x * (lai * time_step * 3600 * 18) / 10**6
