# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_create_soil_parameters.ipynb.

# %% auto 0
__all__ = ['create_soil_parameters']

# %% ../nbs/13_create_soil_parameters.ipynb 3
from typing import Dict
from pathlib import Path
from .create_modeling_options import create_modeling_options

# %% ../nbs/13_create_soil_parameters.ipynb 4
def create_soil_parameters(file_path: Path, # Path to a csv file containing parameter values i.e path/to/parameter_values.csv
                           modeling_options, # Dictionary created using the `create_modeling_options` function
                           list_of_parameters = None, # A list containing the necessary input parameters instead of reading them in file. Will only be used if 'filePath' arguement is not provided
                           default_soil = False, # A logical value indicating whether a default soil should be used  to run tests
                           off_set_psoil = 0, # A numerical value indicating the offset in soil water potential (default = 0)
                           psoil_at_field_capacity = 33

) -> Dict:
    """
    Create a list with soil parameters to run SureauR
    """
    pass
    # Make sure that simulation_parameters and modeling_options are dictionaries -----------------------------
    #assert isinstance(
    #    simulation_parameters, Dict
    #), f"simulation_parameters must be a dictionary not a {type(simulation_parameters)}"

    #assert isinstance(
    #    modeling_options, Dict
    #), f"modeling_options must be a dictionary not a {type(modeling_options)}"


