# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_potential_par.ipynb.

# %% auto 0
__all__ = ['declination']

# %% ../nbs/08_potential_par.ipynb 3
from math import cos, sin, atan

# %% ../nbs/08_potential_par.ipynb 4
def declination(doy: int):  # julian day (day of the year)
    "Calculate declination of sun (radians ? ) for a given julian day (DOY)"

    # Hervé's formula for solar declination

    # Sin(23.5*pi/180), 23.5 = Earth declination

    # Constans ----------------------------------------------------------------
    c1 = 0.398749068925246

    c2 = 2 * 3.1416 / 365

    # date of spring
    c3 = 80

    x = c1 * sin((doy - c3) * c2)  # ;

    # Return declination ------------------------------------------------------
    return atan(x / ((1 - x * x) ^ 0.5))
