# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_4_osmo_comp.ipynb.

# %% auto 0
__all__ = ['osmo_comp']

# %% ../nbs/10_4_osmo_comp.ipynb 3
import numpy as np


# %% ../nbs/10_4_osmo_comp.ipynb 4
# Osmotic potential
def osmo_comp(pi_ft:float, # Osmotic potential at full turgor (MPa)
              r_stemp:float # Unknown parameter definition
              ) -> float:

        "Compute osmotic potential"
        return pi_ft / (1 - r_stemp)
