# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_7_plc_comp.ipynb.

# %% auto 0
__all__ = ['plc_comp']

# %% ../nbs/10_7_plc_comp.ipynb 3
import numpy as np

# %% ../nbs/10_7_plc_comp.ipynb 4
def plc_comp(p_min:float, # Unknown parameter
             slope:float, # Unknown parameter
             p50:float, # Unknown parameter
             ) -> float:

    "Compute Percentage loss of conductivity"

    return 100 / (1 + np.exp(slope / 25 * (p_min - p50)))

