# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_5_psi_total_symp_comp.ipynb.

# %% auto 0
__all__ = ['psi_total_symp_comp']

# %% ../nbs/10_5_psi_total_symp_comp.ipynb 3
from .turgor_comp import turgor_comp
from .osmo_comp import osmo_comp

import numpy as np


# %% ../nbs/10_5_psi_total_symp_comp.ipynb 4
def psi_total_symp_comp(pi_ft:float, # Osmotic potential at full turgor (MPa)
                        e_symp:float, # Modulus of elastoicoty of the Symplasm (MPa/%)
                        r_stemp:float # Unknown parameter
                        ) -> float:

        "Compute Total potential"
        turgor_comp = turgor_comp(pi_ft = pi_ft,
                           e_symp = e_symp,
                           r_stemp = r_stemp)

        osmo_comp = osmo_comp(pi_ft = pi_ft,
                              r_stemp = r_stemp)

        return turgor_comp + osmo_comp
