# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_rg_conversions.ipynb.

# %% auto 0
__all__ = ['rg_convertions']

# %% ../nbs/07_rg_conversions.ipynb 3
def rg_convertions(
    rg_watts: float = None,  # instantaneous radiation (watt)
    rg_mj: float = None,  # instantaneous radiation (in Mega Jule?)
    nhours: float = None, # Unknown parameter definition
)->float:
    "Convert instantaneous radiation in watt to dialy cumulative radiation in MJ (MJ.day-1)"

    if rg_watts is not None and rg_mj is None:
        print("Conversion of rg from watts to Mega Jules")

        # Conversion from watts to Mega Jules
        return rg_watts * 0.0864

    if rg_mj is not None and rg_watts is None and nhours is None:
        print("Conversion of rg from Mega Jules to Watts")

        # Conversion from Mega Jules to watts
        return rg_mj * (1 / 0.0864)

    if rg_mj is not None and rg_watts is None and nhours is not None:
        print("Conversion of rg from Mega Jules to Watts/hour")

        # Conversion from Mega Jules to watts/hour
        return rg_mj * (10**6 / (nhours * 3600))

    elif rg_mj is not None and rg_watts is not None:
        return print("Select one conversion rg_mj or rg_watts")

    else:
        print("No conversions performed")
