# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_ppfd_umol_to_rg_watt.ipynb.

# %% auto 0
__all__ = ['ppfd_umol_to_rg_watt', 'rg_watt_to_ppfd_umol']

# %% ../nbs/06_ppfd_umol_to_rg_watt.ipynb 3
def ppfd_umol_to_rg_watt(
    ppfd: float,  # Photosynthetic photon flux density (umol.m-2.s-1)
    j_to_mol: float = 4.6,  # Conversion factor
    frac_par: float = 0.5,  # Function of solar rdiation that is photosynthetically active radiation (PAR)
):
    "Convert ppfd (umol) to rg (watt)"

    # calculate Global radiation (rg)(W/m2) ----------------------------------------------
    rg = ppfd / frac_par / j_to_mol
    return rg

# %% ../nbs/06_ppfd_umol_to_rg_watt.ipynb 4
def rg_watt_to_ppfd_umol(
    rg: float,  # Global radiation (W/m2)
    j_to_mol: float = 4.6,  # Conversion factor
    frac_par: float = 0.5,  # Function of solar rdiation that is photosynthetically active radiation (PAR)
):
    "Convert rg (watt) to ppfd (umol)"

    # calculate Photosynthetic photon flux density (umol.m-2.s-1) ----------------------------------------------

    return rg * frac_par * j_to_mol
