# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_6_stomatal_regulation_turgor.ipynb.

# %% auto 0
__all__ = ['stomatal_regulation_turgor']

# %% ../nbs/10_6_stomatal_regulation_turgor.ipynb 3
import numpy as np

# %% ../nbs/10_6_stomatal_regulation_turgor.ipynb 4
def stomatal_regulation_turgor(turgor_pressure:float, # Turgor pressure
                               max_turgor_pressure:float, # Maximum turgor pressure,
                               e_max:float, # Unknown parameter
                               e_cuti:float # Residual Transpiration
                               ) -> np.array:
    "This function computes stomatal regulation if stomatal closure is limited (linearly) by turgor pressure"

    # Create np.array for storing values
    stomatal_reg_array = np.zeros(0, dtype=float)


    # Get the lowest value
    tr = min((e_max * turgor_pressure/ max_turgor_pressure), e_max)

    # Append to array
    stomatal_reg_array = np.append(stomatal_reg_array, max(tr, 0))

    # Horrible line but I don't know how to improve it
    # Don't know the meaning of 0 + e_cuti
    horror_line = min(max(max(tr, 0) + e_cuti, 0 + e_cuti), e_max)

    stomatal_reg_array = np.append(stomatal_reg_array, horror_line)

    return stomatal_reg_array

