# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/20_sureau_core_soil.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/20_sureau_core_soil.ipynb 3
import warnings
import collections
import numpy as np
from typing import Dict
from pandera.typing import DataFrame
from sureau_ecos_py.climate_utils import (
    day_length,
    compute_pet,
    potential_par,
    rg_units_conversion,
    compute_vpd_from_t_rh,
    calculate_rh_diurnal_pattern,
    rg_watt_ppfd_umol_conversions,
    calculate_radiation_diurnal_pattern,
    calculate_temperature_diurnal_pattern,
)
from sureau_ecos_py.create_simulation_parameters import (
    create_simulation_parameters,
)
from .create_climate_data import create_climate_data
from .create_modeling_options import create_modeling_options

# %% ../nbs/20_sureau_core_soil.ipynb 4
#def new_sureau_soil(
#    climate_data: DataFrame,  # Dataframe created using the `create_climate_data` function
#    year: int,  # Year,
#    day_of_year: int,  # Day of the year
#) -> Dict:  # Dictionary containing parameters to run the model
#    'Create a list with all necessary daily climate values to run SureauR from climate_data'
#
#    # Assert parameters ---------------------------------------------------------
#    pass

