# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/17_wg_clim.ipynb.

# %% auto 0
__all__ = ['new_wb_clim']

# %% ../nbs/17_wg_clim.ipynb 3
import collections
from typing import Dict
from pandera.typing import DataFrame
from .create_stand_parameters import create_stand_parameters
from .create_climate_data import create_climate_data


# %% ../nbs/17_wg_clim.ipynb 4
def new_wb_clim(
    climate_data:DataFrame, # Dataframe created using the `create_climate_data` function
    year:int, # Year, __No definition found__
    doy:int # Day of the year, __No definition found__


) -> Dict:  # Dictionary containing parameters to run the model
    "Create a list with all necessary daily climate values to run SureauR from climate_data"

    # Assert parameters ---------------------------------------------------------

    # Year
    assert isinstance(
        year, int
    ) and 3000 >= year > 0,"year must be a integer value between 0-3000"

    # Day of year
    assert isinstance(
        doy, int
    ) and 368 >= doy >= 1, "doy must be a integer value between 1-365"

    # Create wb_clim dictionary -------------------------------------------------
    wb_clim_dict = collections.defaultdict(list)

    # Add parameters ------------------------------------------------------------
    wb_clim_dict['year'] = year
    wb_clim_dict['doy'] = doy

    return wb_clim_dict








